# basic
title: Rust 中文社区
subtitle: Rust 编程语言中文社区，国内最活跃、资源最集中的 Rust 技术社区
favicon: favicon.ico
avatar: images/avatar.png

# disqus
# disqus_shortname: rustchina

# social
social:
  github: https://github.com/RustChina
  twitter: https://twitter.com/rustlang
  weibo: http://weibo.com/RustChina

# nav #
nav:
  home: .
  archive: archives
  chat: https://chat.rust-china.org
  wiki: https://wiki.rust-china.org
  translation: translation
  rss: atom.xml
  about: about

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
